/**
 * @file src/utils/strings.ts
 * @description Utility helpers and shared logic.
 * @lastUpdated 2025-09-19T11:33:09.057Z
 */

import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  'en-US': {
    rasdPay: 'RASD Pay',
    signIn: 'Sign in to your RASD Pay account',
    welcomeBack: 'Welcome Back',
    phone: 'Phone',
    email: 'Email',
    emailAddress: 'Email Address',
    enterYourEmail: 'Enter your email',
    rememberMe: 'Remember me',
    continue: 'Continue',
    customerSupport: 'Customer Support',
    enterVerificationCode: 'Enter Verification Code',
    sentCodeMessage: 'We’ve sent a 4 digit code to your email',
    resendIn: 'Resend in ',
    seconds: 'seconds',
    totalBalance: 'Total balance',
    fundReceived: 'FUND RECEIVED',
    fundSpent: 'FUND SPENT',
    walletSummary: 'Wallet Summary',
    remainingBalance: 'Remaining Balance',
    home: 'Home',
    upload: 'Upload',
    expenses: 'Expenses',
    profile: 'Profile',
    expenseHistory: 'Expense History',
    all: 'All',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    viewReceipt: 'View Receipt',
    submittedDate: 'Submitted date',
    vendor: 'Vendor',
    amount: 'Amount',
    downloadReceipt: 'Download Receipt',
    details: 'Details',
    notifications: 'Notifications',
    profileSettings: 'Profile & Settings',
    language: 'Language',
    chooseLanguage: 'Choose your preferred language',
    biometricLogin: 'Biometric Login',
    fingerprintOrFaceId: 'Use fingerprint or face ID',
    appNotifications: 'App Notifications',
    receivePushNotifications: 'Receive Push Notifications',
    preferences: 'PREFERENCES',
    accountSecurity: 'ACCOUNT SECURITY',
    changePassword: 'Change Password',
    updatePassword: 'Update your account password',
    logout: 'Logout',
    ResendCode: 'Resend Code',
    myWallet: 'My Wallet',
    expenseApproved: 'Expense Approved',
    expenseRejected: 'Expense Rejected',
    priceAlert: 'Price Alert',
    budgetWarning: 'Budget Warning',
    invalidEmail: 'Invalid Email',
    enterValidEmail: 'Please enter a valid email address',
    invalidPhone: 'Invalid Phone',
    enterValidPhone: 'Please enter a valid phone number (8-15 digits)',
    pleaseWait: 'Please wait...',
    verificationFailed: 'Verification failed',
    invalidCode: 'Invalid code, please try again.',
    guest: 'Guest',
    loading: 'Loading...',
    noDetails: 'No details found',
    noReceipt: 'No receipt uploaded',
    appVersion: 'App Version 1.0.0',
    deleteNotification: 'Delete Notification',
    deleteNotificationConfirm: 'Are you sure you want to delete this notification?',
    cancel: 'Cancel',
    delete: 'Delete',
    close: 'Close',
  },

  'ar-SA': {
    rasdPay: 'RASD Pay',
    signIn: 'تسجيل الدخول إلى حساب RASD Pay الخاص بك',
    welcomeBack: 'مرحباً بعودتك',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    emailAddress: 'عنوان البريد الإلكتروني',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    rememberMe: 'تذكرني',
    continue: 'استمرار',
    customerSupport: 'دعم العملاء',
    enterVerificationCode: 'أدخل رمز التحقق',
    sentCodeMessage: 'لقد أرسلنا رمز مكون من 4 أرقام إلى بريدك الإلكتروني',
    resendIn: 'إعادة الإرسال خلال ',
    seconds: 'ثواني',
    totalBalance: 'الرصيد الكلي',
    fundReceived: 'تم استلام الأموال',
    fundSpent: 'تم صرف الأموال',
    walletSummary: 'ملخص المحفظة',
    remainingBalance: 'الرصيد المتبقي',
    home: 'الرئيسية',
    upload: 'تحميل',
    expenses: 'المصروفات',
    profile: 'الملف الشخصي',
    expenseHistory: 'سجل المصروفات',
    all: 'الكل',
    pending: 'قيد الانتظار',
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    viewReceipt: 'عرض الإيصال',
    submittedDate: 'تاريخ التقديم',
    vendor: 'البائع',
    amount: 'المبلغ',
    downloadReceipt: 'تحميل الإيصال',
    details: 'التفاصيل',
    notifications: 'الإشعارات',
    profileSettings: 'الملف الشخصي والإعدادات',
    language: 'اللغة',
    chooseLanguage: 'اختر لغتك المفضلة',
    biometricLogin: 'تسجيل الدخول البيومتري',
    fingerprintOrFaceId: 'استخدام بصمة الإصبع أو معرف الوجه',
    appNotifications: 'إشعارات التطبيق',
    receivePushNotifications: 'تلقي إشعارات الدفع',
    preferences: 'التفضيلات',
    accountSecurity: 'أمان الحساب',
    changePassword: 'تغيير كلمة المرور',
    updatePassword: 'تحديث كلمة مرور حسابك',
    logout: 'تسجيل الخروج',
    ResendCode: 'إعادة إرسال الرمز',
    myWallet: 'محفظتي',
    expenseApproved: 'تمت الموافقة على المصروف',
    expenseRejected: 'تم رفض المصروف',
    priceAlert: 'تنبيه السعر',
    budgetWarning: 'تحذير الميزانية',
    invalidEmail: 'بريد إلكتروني غير صالح',
    enterValidEmail: 'يرجى إدخال عنوان بريد إلكتروني صالح',
    invalidPhone: 'هاتف غير صالح',
    enterValidPhone: 'يرجى إدخال رقم هاتف صالح (8-15 رقمًا)',
    pleaseWait: 'يرجى الانتظار...',
    verificationFailed: 'فشل التحقق',
    invalidCode: 'رمز غير صالح، يرجى المحاولة مرة أخرى.',
    guest: 'ضيف',
    loading: 'جارٍ التحميل...',
    noDetails: 'لم يتم العثور على تفاصيل',
    noReceipt: 'لم يتم رفع إيصال',
    appVersion: 'إصدار التطبيق 1.0.0',
    deleteNotification: 'حذف الإشعار',
    deleteNotificationConfirm: 'هل أنت متأكد أنك تريد حذف هذا الإشعار؟',
    cancel: 'إلغاء',
    delete: 'حذف',
    close: 'إغلاق',
  },
});

export default strings;
