import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings( {
    'en-US': {
        addFriend: "Add Friend",
        phone: "Phone",
        enterPhone: "Enter phone",
        email: "Email",
        enterEmail: "Enter email",
        userCode: "User code",
        enterUserCode: "Enter user code",
        continue: "Continue",
        startChat: "Start Chat",
        cancel: "Cancel",
        userNotFound: "User not found, please try again!",
        tryAgain: "Try Again",
        createGroup: "Create Group",
        members: "Members",
        addMembersToGroup: "Add members to group",
        add: "Add",
        nameGroup: "Name Group",
        enterGroupName: "Enter group name",
        messages: "Messages",
        typeMessage: "Type a message ...",
        media: "Media",
        deleteChat: "Delete Chat",
        never: "Never",
        profile: "Profile",
        day01: "01 Day",
        day05: "05 Days",
        day07: "07 Days",
        today: "Today",
        yesterday: "Yesterday",
        tapToViewGroupInfo: "Tap to view group info.",
        camera: "Camera",
        gallery: "Gallery",
        info: "Info",
        delete: "Delete",
        readBy: "Read by",
        unreadBy: "Unread by",
        seeAllMembers: "See all members",
        leaveGroup: "Leave Group",
        leaveGroupConfirmation: "Are you sure you want to leave this group?",
        deleteAccountConfirm: "Are you sure you want to delete your account?",
        yesLeave: "Yes, Leave",
        noCancel: "No, Cancel",
        language: "Language",
        termsOfService: "Term of Service",
        privacyPolicy: "Privacy Policy",
        aboutApp: "About App",
        contactSupport: "Contact & Support",
        deleteAccount: "Delete Account",
        logout: "Logout",
        editProfile: "Edit Profile",
        saveChanges: "Save Changes",
        changesSaved: "Changes are Saved!",
        yesDelete: "Yes, Delete",
        yesLogout: "Yes, Logout",
        noContinue: "No, Continue",
        logoutConfirm: "Are you sure you want to logout?",
        MyChat: "MyChat",
        search: "Search",
        name: "Name",
        removeUserFromGroupConfirmation: "Are you sure you want to remove this user from the group?",
        reachUsAt: "Reach us at",
        yesRemove: "Yes, Remove",
        groupMembers: "Group Members",
        editGroup: "Edit Group",
        unread: "Unread",
        readAt: "Read At",
        sentAt: "Sent At",
        day: "Day",
        days: "Days",
        deletedUser: "Deleted User",

    },
    'th-TH': {
        addFriend: "เพิ่มเพื่อน",
        phone: "โทรศัพท์",
        enterPhone: "กรอกหมายเลขโทรศัพท์",
        email: "อีเมล",
        enterEmail: "กรอกอีเมล",
        userCode: "รหัสผู้ใช้",
        enterUserCode: "กรอกรหัสผู้ใช้",
        continue: "ดำเนินการต่อ",
        startChat: "เริ่มแชท",
        cancel: "ยกเลิก",
        userNotFound: "ไม่พบผู้ใช้ โปรดลองอีกครั้ง!",
        tryAgain: "ลองอีกครั้ง",
        createGroup: "สร้างกลุ่ม",
        members: "สมาชิก",
        addMembersToGroup: "เพิ่มสมาชิกเข้ากลุ่ม",
        add: "เพิ่ม",
        nameGroup: "ตั้งชื่อกลุ่ม",
        messages: "ข้อความ",
        typeMessage: "พิมพ์ข้อความ ...",
        media: "สื่อ",
        deleteChat: "ลบแชท",
        never: "ไม่เคย",
        profile: "โปรไฟล์",
        day01: "01 วัน",
        day05: "05 วัน",
        day07: "07 วัน",
        today: "วันนี้",
        yesterday: "เมื่อวาน",
        tapToViewGroupInfo: "แตะเพื่อดูข้อมูลกลุ่ม",
        camera: "กล้อง",
        gallery: "แกลเลอรี",
        info: "ข้อมูล",
        delete: "ลบ",
        readBy: "อ่านแล้วโดย",
        unreadBy: "ยังไม่อ่านโดย",
        seeAllMembers: "ดูสมาชิกทั้งหมด",
        leaveGroup: "ออกจากกลุ่ม",
        deleteAccountConfirm: "คุณแน่ใจหรือว่าต้องการลบบัญชีของคุณ?",
        yesLeave: "ใช่, ออก",
        noCancel: "ไม่, ยกเลิก",
        language: "ภาษา",
        termsOfService: "ข้อตกลงการใช้บริการ",
        privacyPolicy: "นโยบายความเป็นส่วนตัว",
        aboutApp: "เกี่ยวกับแอป",
        contactSupport: "ติดต่อ & สนับสนุน",
        deleteAccount: "ลบบัญชี",
        logout: "ออกจากระบบ",
        editProfile: "แก้ไขโปรไฟล์",
        saveChanges: "บันทึกการเปลี่ยนแปลง",
        changesSaved: "บันทึกการเปลี่ยนแปลงแล้ว!",
        yesDelete: "ใช่, ลบ",
        yesLogout: "ใช่, ออกจากระบบ",
        noContinue: "ไม่, ดำเนินการต่อ",
        logoutConfirm: "คุณแน่ใจหรือว่าต้องการออกจากระบบ?",
        MyChat: "MyChat",
        enterGroupName: "กรอกชื่อกลุ่ม",
        search: "ค้นหา",
        name: "ชื่อ",
        reachUsAt: "ติดต่อเราได้ที่",
        removeUserFromGroupConfirmation: "คุณแน่ใจหรือไม่ว่าต้องการลบผู้ใช้นี้ออกจากกลุ่ม",
        yesRemove: "ใช่ ลบ",
        leaveGroupConfirmation: "คุณแน่ใจหรือไม่ว่าต้องการออกจากกลุ่มนี้",
        groupMembers: "สมาชิกกลุ่ม",
        editGroup: "แก้ไขกลุ่ม",
        unread: "ยังไม่ได้อ่าน",
        readAt: "อ่านเมื่อ",
        sentAt: "ส่งเมื่อ",
        day: "วัน",
        days: "วัน",
        deletedUser: "ผู้ใช้ที่ถูกลบ",


    },
} );

export default strings;
