import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings( {
    'en-US': {
        rasdPay: 'RASD Pay',
        signIn: 'Sign in to your RASD Pay account',
        welcomeBack: 'Welcome Back',
        phone: 'Phone',
        email: 'Email',
        emailAddress: 'Email Address',
        enterYourEmail: 'Enter your email',
        rememberMe: 'Remember me',
        continue: 'Continue',
        customerSupport: 'Customer Support',
        enterVerificationCode: 'Enter Verification Code',
        sentCodeMessage: 'We’ve sent a 4 digit code to your email',
        resendIn: 'Resend in ',
        seconds: 'seconds',
        invalidCode: 'Invalid code, try again',
        totalBalance: 'Total balance',
        fundReceived: 'FUND RECEIVED',
        fundSpent: 'FUND SPENT',
        walletSummary: 'Wallet Summary',
        remainingBalance: 'Remaining Balance',
        home: 'Home',
        upload: 'Upload',
        expenses: 'Expenses',
        profile: 'Profile',
        expenseHistory: 'Expense History',
        all: 'All',
        pending: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        viewReceipt: 'View Receipt',
        submittedDate: 'Submitted date',
        vendor: 'Vendor',
        amount: 'Amount',
        downloadReceipt: 'Download Receipt',
        details: 'Details',
        notifications: 'Notifications',
        profileSettings: 'Profile & Settings',
        language: 'Language',
        chooseLanguage: 'Choose your preferred language',
        biometricLogin: 'Biometric Login',
        fingerprintOrFaceId: 'Use fingerprint or face ID',
        appNotifications: 'App Notifications',
        receivePushNotifications: 'Receive Push Notifications',
        preferences: 'PREFERENCES',
        accountSecurity: 'ACCOUNT SECURITY',
        changePassword: 'Change Password',
        updatePassword: 'Update your account password',
        logout: 'Logout',
        ResendCode: 'Resend Code',
        myWallet: 'My Wallet',

    },

    'ar-SA': {
        rasdPay: 'RASD Pay',
        signIn: 'تسجيل الدخول إلى حساب RASD Pay الخاص بك',
        welcomeBack: 'مرحباً بعودتك',
        phone: 'الهاتف',
        email: 'البريد الإلكتروني',
        emailAddress: 'عنوان البريد الإلكتروني',
        enterYourEmail: 'أدخل بريدك الإلكتروني',
        rememberMe: 'تذكرني',
        continue: 'استمرار',
        customerSupport: 'دعم العملاء',
        enterVerificationCode: 'أدخل رمز التحقق',
        sentCodeMessage: 'لقد أرسلنا رمز مكون من 4 أرقام إلى بريدك الإلكتروني',
        resendIn: 'إعادة الإرسال خلال ',
        seconds: 'ثواني',
        invalidCode: 'رمز غير صالح، حاول مرة أخرى',
        totalBalance: 'الرصيد الكلي',
        fundReceived: 'تم استلام الأموال',
        fundSpent: 'تم صرف الأموال',
        walletSummary: 'ملخص المحفظة',
        remainingBalance: 'الرصيد المتبقي',
        home: 'الرئيسية',
        upload: 'تحميل',
        expenses: 'المصروفات',
        profile: 'الملف الشخصي',
        expenseHistory: 'سجل المصروفات',
        all: 'الكل',
        pending: 'قيد الانتظار',
        approved: 'موافق عليه',
        rejected: 'مرفوض',
        viewReceipt: 'عرض الإيصال',
        submittedDate: 'تاريخ التقديم',
        vendor: 'البائع',
        amount: 'المبلغ',
        downloadReceipt: 'تحميل الإيصال',
        details: 'التفاصيل',
        notifications: 'الإشعارات',
        profileSettings: 'الملف الشخصي والإعدادات',
        language: 'اللغة',
        chooseLanguage: 'اختر لغتك المفضلة',
        biometricLogin: 'تسجيل الدخول البيومتري',
        fingerprintOrFaceId: 'استخدام بصمة الإصبع أو معرف الوجه',
        appNotifications: 'إشعارات التطبيق',
        receivePushNotifications: 'تلقي إشعارات الدفع',
        preferences: 'التفضيلات',
        accountSecurity: 'أمان الحساب',
        changePassword: 'تغيير كلمة المرور',
        updatePassword: 'تحديث كلمة مرور حسابك',
        logout: 'تسجيل الخروج',
        ResendCode: 'إعادة إرسال الرمز', 
        myWallet: 'محفظتي',

    },
} );

export default strings;
